### ISSUE TITLE
How to edit NODE's property in Flutter?

### ISSUE THREAD

**Issue by sulater** [2d-inc/Nima-Flutter#2]
Like this:
![gif](https://cdn.2dimensions.com/manual/solo2.gif )

**Comment by luigi-rosso** [comment]
We'll be extending the example to include some controllers that will make this easier to do in Flutter soon. Right now you can do this by extending the logic in [nima_actor.dart](https://github.com/2d-inc/Nima-Flutter/blob/master/lib/nima_actor.dart).

You would query for the node when you want to change it:
```
ActorNode eyes = _actor.getNode("Eyes");
if(eyes is ActorNodeSolo)
{
	eyes.activeChildIndex = 0; // set to closed
	eyes.activeChildIndex = 1; // .. or set to open
	eyes.activeChildIndex = 2; // .. or set to angry
}
```

I'll post a note when we have an example specifically showing how to do this on top of the existing example.

**Comment by sulater** [comment]
thanks so much, 👍
