### ISSUE TITLE
Error on release build

### ISSUE THREAD

**Issue by carnivash** [2d-inc/Nima-Flutter#3]
I'm getting this error: 

flutter: Loading actor filename assets/animation/welcome
[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
RangeError (length): Invalid value: Not in range 0..8, inclusive: 8
#0      _List.[]= (dart:core/runtime/libarray.dart:0)
#1      Actor.readComponentsBlock (package:nima/nima/actor.dart:560)
#2      Actor.load (package:nima/nima/actor.dart:421)
#3      FlutterActor.loadFromBundle (package:nima/nima.dart:197)
<asynchronous suspension>

On debug mode it's fine, this happens only if i run the release build.
Thanks.

**Comment by luigi-rosso** [comment]
This was due to a Dart AOT compiler bug which the Dart team fixed! Closing.
