### ISSUE TITLE
Export generates a .nma instead of .nima?

### ISSUE THREAD

**Issue by sebstr1** [2d-inc/Nima-Flutter#6]
I followed the steps for exporting to flutter, selecting export to engine, type generic, leaving the rest as default. This generates a zip with a .nma file instead of a .nima file which does not seem to be usable in flutter.

Update: I tried to manually change the file ending from .nma to .nima and then it works.

**Comment by luigi-rosso** [comment]
I've published the updated package to Dart Pub which should fix this issue. Make sure you reference the full filename when providing the asset to the actor widget!

**Comment by luigi-rosso** [comment]
Closing but feel free to reopen if you're still having problems.

**Comment by Idan-BM** [comment]
I don't understand, how do i fix this?

**Comment by luigi-rosso** [comment]
Call “flutter pub upgrade” from the terminal to update your packages. That should grab the latest flare_flutter dependency.

**Comment by Idan-BM** [comment]
You ment "nima_flutter"?
Also when running my .nima file on your example i get animation for 0.5s and then pause for couple of seconds and continues, you know why?
