### ISSUE TITLE
Completed callback is not being call

### ISSUE THREAD

**Issue by yrmartinez** [2d-inc/Nima-Flutter#8]
I'm using the latest version of the package (v 1.0.2) but the completed callback is not being call, animation status is always the last one called, either jump or attack.

**Comment by luigi-rosso** [comment]
Are you using the example app or are you testing with your own code/animations?

Note that looping animations won't trigger the callback. Let me know, happy to look at the source if you're willing to provide it.

**Comment by yrmartinez** [comment]
@luigi-rosso Thanks for your quick response.

I'm just exported the animation again and it worked as expected, it was an exporting mistake, leaving one of the animations in a loop.

Thanks again!

**Comment by luigi-rosso** [comment]
np! Thanks for using Nima!
